// <auto-generated />
using System;
using ApiAnimais.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiAnimais.Migrations
{
    [DbContext(typeof(AnimalContext))]
    [Migration("20250413001007_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ApiAnimais.Models.AnimalCuidado", b =>
                {
                    b.Property<Guid>("AnimalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CuidadoId")
                        .HasColumnType("TEXT");

                    b.HasKey("AnimalId", "CuidadoId");

                    b.HasIndex("CuidadoId");

                    b.ToTable("AnimaisCuidados");
                });

            modelBuilder.Entity("ApiAnimais.Models.AnimalModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Especie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Habitat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaisOrigem")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("ApiAnimais.Models.CuidadoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cuidados");
                });

            modelBuilder.Entity("ApiAnimais.Models.AnimalCuidado", b =>
                {
                    b.HasOne("ApiAnimais.Models.AnimalModel", "Animal")
                        .WithMany("Cuidados")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiAnimais.Models.CuidadoModel", "Cuidado")
                        .WithMany("Animais")
                        .HasForeignKey("CuidadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Cuidado");
                });

            modelBuilder.Entity("ApiAnimais.Models.AnimalModel", b =>
                {
                    b.Navigation("Cuidados");
                });

            modelBuilder.Entity("ApiAnimais.Models.CuidadoModel", b =>
                {
                    b.Navigation("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
